apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: put-to-topic
  namespace: redhat-rhmi-camel-k
spec:
  sources:
  - content: |
      // camel-k: language=java
      import org.apache.camel.builder.RouteBuilder;

      public class PutToTopic extends RouteBuilder {
        @Override
        public void configure() throws Exception {
            // try things like all, Banana, Orange, Tomato
            from("timer://foo?repeatCount=1")
              .setBody()
                .simple("all")
              .to("kafka:producer?brokers=rhmi-cluster-kafka-bootstrap.redhat-rhmi-amq-streams:9092");
        }
      }
    name: PutToTopic.java
